version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code:z
      - ./src/media:/code/src/media:z
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - .env

volumes:
  media: