# Generated by Django 4.2.5 on 2023-09-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiermodel",
            name="change_expiration_time_perm",
            field=models.BooleanField(
                default=False, null=True, verbose_name="CHANGE EXPIRE TIME PERMISSION"
            ),
        ),
    ]
