# Generated by Django 4.2.5 on 2023-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_tiermodel_change_expiration_time_perm"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlexpirationmodel",
            name="img_filename",
            field=models.CharField(null=True),
        ),
    ]
