# Generated by Django 4.2.5 on 2023-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_urlexpirationmodel_img_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("picture", models.FileField(upload_to="media/")),
            ],
        ),
    ]
