# Generated by Django 4.2.5 on 2023-09-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="img",
            field=models.FileField(upload_to="media/"),
        ),
    ]
