# Generated by Django 4.2.5 on 2023-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_imagemodel_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemodel",
            name="img",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
