# Generated by Django 4.2.5 on 2023-09-24 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_imagemodel_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
